version: 0.2

phases:
  build:
    commands:
      - echo "Build phase - nothing to do for a static website"

  post_build:
    commands:
      - aws s3 cp ./index.html s3://cs412isabolik.xyz/ --cache-control "max-age=60" --metadata-directive REPLACE --expires 2034-01-01T00:00:00Z --acl public-read
      - aws s3 cp ./projects/ s3://cs412isabolik.xyz/projects/ --recursive --exclude "*" --include "*.html" --cache-control "max-age=60" --metadata-directive REPLACE --expires 2034-01-01T00:00:00Z --acl public-read

artifacts:
  files: '**/*'
