version: 0.2

phases:
  build:
    commands:
      - echo "Build phase - nothing to do for a static website"

  post_build:
    commands:
      - aws s3 sync ./index.html s3://cs412isabolik.xyz/ --cache-control "max-age=60"
      - aws s3 sync ./projects/ s3://cs412isabolik.xyz/projects/ --recursive --exclude "*" --include "*.html" --cache-control "max-age=60" 
      - aws cloudfront create-invalidation --distribution-id EM3YHELT6V6LA --paths "/*"
artifacts:
  files: '**/*'
