version: 0.2

phases:
  build:
    commands:
      - echo "Build phase - nothing to do for a static website"

  post_build:
    commands:
      - aws s3 sync ./ s3://your-s3-bucket-name/ --exclude "*" --include "index.html" --include "projects/*.html" --cache-control "max-age=60"

artifacts:
  files: '**/*'
